version: '3'
services:
  node-app:
    build: .
    volumes:
      - ./:/app:ro
      - /app/node_modules
    ports:
      - '5000:5001'
    environment:
      - PORT=5001
    #env_file:
    #  - ./.env
